### ISSUE TITLE
Fails with Mojolicious 6.0 and later

### ISSUE THREAD

**Issue by andk** [avkhozov/test-mojo-session#3]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/52071858

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by avkhozov** [comment]
Thanks for report, but this report for Test::Mojo::Session version 1.02.
In version 1.04 this was fixed: https://metacpan.org/changes/distribution/Test-Mojo-Session#L3

**Comment by andk** [comment]
Sorry for the noise. I suppose the different capitalization (test-mojo-session vs Test-Mojo-Session) confused me. I'll try to prevent that his pops up again.
