### ISSUE TITLE
Don't duplicate Mojolicious::Sessions code

### ISSUE THREAD

**Issue by kraih** [avkhozov/test-mojo-session#7]
The way this module replicates the behaviour of `Mojolicious::Sessions` to extract session data is broken and unnecessary. You could just use a mock controller like [this openQA function](https://github.com/os-autoinst/openQA/commit/1c3a3cfdad0d3306a3bc94603477fa375aaaefe4#diff-17f8fff99c9cee36235c85b62eaeb185R53) does.

**Comment by avkhozov** [comment]
Thank you for the hint
